before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - rustc src/lib.rs
  - rustc example1.rs -Lsrc && ./example1 --no-show
  - rustc example2.rs -Lsrc && ./example2 --no-show
