[package]

name = "gnuplot"
version = "0.0.0"
authors = [ "SiegeLord <slabode@aim.com>" ]

[[lib]]

name = "gnuplot"
path = "src/lib.rs"

[[bin]]

name = "example1"
path = "examples/example1.rs"

[[bin]]

name = "example2"
path = "examples/example2.rs"

[[bin]]

name = "example3"
path = "examples/example3.rs"
